apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleserver
  template:
    metadata:
      labels:
        app: simpleserver
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: simpleserver
          image: domantas231/the-project:1.13
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_PATH
              value: "/usr/src/app/files/image.jpg"