apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: database-login
stringData:
    postgres_user: ENC[AES256_GCM,data:T1ZV7Q==,iv:XT5Scga2liFcjgEyxTBoIbfWeF98uiVmD6e/Vgax4dY=,tag:33nNmo/W6++LSRJnks589w==,type:str]
    postgres_password: ENC[AES256_GCM,data:cicQiP/yM/8=,iv:1jsU1Yh9WW8Sbhng9dlSajeHgMk1kheTX/6021CSbAo=,tag:04oz0EFH/M1szJkGfi0y0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEengrMk9tWTE4R2FWQW90
            Q3hQZlBvZFozUVdxL1Y2eFZrbERHYk8yYzBZCmZEZFpraTRtRDYybWFTUnEwZm9N
            RlFSTSs2aFRGQWRSMDJ0azUyakYya1kKLS0tIHBESk5CYzZKTVlUZVFwY0pMTUNk
            cDNDb3BRNnlNSVkyMUFIdVJMUFpnVU0KuhbIcTwSsAS4InZ//jWgL93RMjADkU/f
            D1ho3VGBFJVJd0HXg8TE6TXOaT7fZxdKbHkpHxajvYC0VBMffUr3fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nw7yargqwxceuzwgm4m32ndx4n5k7q6ee07mzz2jlahkpswuc4wsrglysy
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-21T13:53:32Z"
    mac: ENC[AES256_GCM,data:OMjO54wDw5W+w71S0C8sOYwfPLm+u3ft+5L2KwM77Ylys3xSNW2dPRlJZMK9fHXzI2YjC8smHQ4hj47gCSDXR3m45Zl2HjkvmvDRBT+KWE7Fq7f7r80qKvb/6ZYiF6g3TApVBn3h2GMYfNDJk00fhf65mFKxxkleI8IfYtzEwx0=,iv:EyF5gZwEWZj90g8y0sZsmVOS+5EoJDAlg2k4YzAkgyc=,tag:AX7WZqyllf/8axS1ZMk9fA==,type:str]
    version: 3.13.1
