apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: domantas231/ping-pong:3.42
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-login
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-login
                  key: postgres_password