apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: pingpong
          image: domantas231/ping-pong:1.11
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: LOG_FILE
              value: "/usr/src/app/files/log_output.txt"
            - name: COUNTER_FILE
              value: "/usr/src/app/files/counter.txt"