apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: database-login
stringData:
    postgres_user: ENC[AES256_GCM,data:e60Vsw==,iv:bcyNhhy18L1UL4bLYfKj3CsqvzJd5D87pccVmYUnh0U=,tag:d6xFy6orGm28lEvP1AyNQw==,type:str]
    postgres_password: ENC[AES256_GCM,data:ZqzqDGzXyOg=,iv:o8v1vjb3e/LAAPBQp0GcF/eXS6pNPP71PRcLq4ijrNo=,tag:1cdKaq6YGSkOyVcwy/KaBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRUxTSWtwT2FBNGsreC80
            S1lZZmVKVldORFB5NW53cEFQa21yVmluZkY0CitIV0lSWnFHQTlMTzhFN3BwYXdO
            SUZteTFvdHNPVkV6MzM4cmNZQWJaL28KLS0tIFZFYktyU0FWVTZIUjkzaytrLzVq
            RTh1SkNpeVlBSjN6cXF0dG9OZkhrN1EKzEJ1PPlA4NveDrm4x/sxcTPC2ydgebiC
            lDit6po0KPap+257fFWQV/uV3qS9snHNlYkfauJZu3KFqFIqQG+5xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nw7yargqwxceuzwgm4m32ndx4n5k7q6ee07mzz2jlahkpswuc4wsrglysy
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-21T12:41:28Z"
    mac: ENC[AES256_GCM,data:fIlvovg2qEuVfcUQ8xkAM6IA7tQKXiTlF9P0JBOUMENmZ8DWGn86dloqhtHkyzwo1Uwwn3fDQYlwbxhDXOyuw1wSXH6KLBSYds3DRqoIyEkGFuVrlukk205EeMmMFYiLjsuTsySReaowXglhp2hNgkkhQmBDBGvVLVDQ46bfJPE=,iv:7Wl0ut7qolWHKY2n4NuyQNRtl13pWCkgESYUHB41reE=,tag:Ckp0gr5TdfnyRKxfXXgtNQ==,type:str]
    version: 3.13.1
