apiVersion: v1
kind: ConfigMap
metadata:
  namespace: exercises
  name: logoutput-configmap
data:
  port: "3000"
  pings_url: "http://pingpong-svc:80/pings"
  message: "Hello world"
  information_file: "/config/information"
  information: |
    this is text from a file

