apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: hashwriter
          image: domantas231/log-writer:1.10
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: LOG_FILE
              value: "/usr/src/app/files/log_output.txt"
        - name: hashreader
          image: domantas231/log-reader:1.10
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: LOG_FILE
              value: "/usr/src/app/files/log_output.txt"