apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hashgenerator
          image: domantas231/log-output:2.5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: port
            - name: PINGS_URL
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: pings_url
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: message
            - name: INFORMATION_FILE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: information_file
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
      volumes:
      - name: config
        configMap: 
          name: logoutput-configmap
          items:
            - key: "information"
              path: "information"