apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: domantas231/todo-app:2.6
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: port
            - name: IMAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: image_path
            - name: TIME_MS
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: time_ms